// Generated by scripts/generate-sdk-facade.ts.
export {
  BOUNCE_PROBES_PER_FRAME,
  BOUNCE_SETTINGS,
  PROBE_FLOATS,
} from '../../sdk-core/src/bounce/contracts.ts';
export { bounceBatchOf, createBounceBudget } from '../../sdk-core/src/bounce/budget.ts';
export type { BounceBudget } from '../../sdk-core/src/bounce/budget.ts';
export { createBounceCascades } from '../../sdk-core/src/bounce/cascades.ts';
export type { BounceCascadeLevel, BounceCascades } from '../../sdk-core/src/bounce/cascades.ts';
export { createBounceOccupancy } from '../../sdk-core/src/bounce/occupancy.ts';
export type { BounceOccupancy } from '../../sdk-core/src/bounce/occupancy.ts';
export { cloneSceneLight } from '../../sdk-core/src/scene/light/clone.ts';
export { createDefaultLightingSceneLights } from '../../sdk-core/src/lighting/scene/controls.ts';
export { createLightingScene } from '../../sdk-core/src/lighting/scene/experimentScene.ts';
export { createSceneLightStore } from '../../sdk-core/src/scene/light/store.ts';
export type { SceneLightStore } from '../../sdk-core/src/scene/light/store.ts';
export { createShadowPlan } from '../../sdk-core/src/scene/light-shadow/plan.ts';
export type { ShadowPlan } from '../../sdk-core/src/scene/light-shadow/plan.ts';
export { createTransport } from '../../sdk-core/src/lighting/transport/transport.ts';
export { exportLightingGltf } from '../../sdk-core/src/lighting/scene/gltf.ts';
export { LIGHT_FIELD } from '../../sdk-core/src/scene/light/fields.ts';
export {
  LIGHT_KIND,
  LIGHT_SETTINGS,
  MAX_SHADOW_SLICES,
  POINT_FACES,
  SCENE_LIGHT_FLOATS,
  SCENE_LIGHT_HEADER_FLOATS,
  SCENE_LIGHT_VERSION,
} from '../../sdk-core/src/scene/light/contracts.ts';
export type {
  SceneLight,
  SceneLightingView,
  ShadowViewpoint,
} from '../../sdk-core/src/scene/light/contracts.ts';
export type { LightingCapabilities } from '../../sdk-core/src/scene/light/capabilities.ts';
export type {
  LightingSceneLight,
  Patch,
  Scene,
  Surface,
  Vec3,
} from '../../sdk-core/src/lighting/scene/types.ts';
export {
  POINT_FACE_AXES,
  SHADOW_CULL_FLOATS,
  SHADOW_RECORD_FLOATS,
  writeFace,
} from '../../sdk-core/src/scene/light-shadow/faces.ts';
export {
  PROXY_CHILD_WORDS,
  PROXY_CHILDREN,
  PROXY_NODE_FLOATS,
  PROXY_NODE_WORDS,
  PROXY_TRIANGLE_FLOATS,
  SCENE_PROXY_HEADER_WORDS,
  SCENE_PROXY_MAGIC,
  SCENE_PROXY_VERSION,
} from '../../sdk-core/src/contracts/proxy.ts';
export type {
  SceneProxy,
  SceneProxyColumns,
  SceneProxyDescriptor,
} from '../../sdk-core/src/contracts/proxy.ts';
export { regionRect } from '../../sdk-core/src/scene/light-shadow/volume.ts';
export { SHADOW_PAGE } from '../../sdk-core/src/scene/light-shadow/virtual.ts';
export type { ShadowRequestReport } from '../../sdk-core/src/scene/light-shadow/requests.ts';
export { solveTransportOracle } from '../../sdk-core/src/lighting/transport/oracle.ts';
export type {
  TransportOptions,
  TransportProgress,
  TransportResult,
  TransportSnapshot,
} from '../../sdk-core/src/lighting/transport/contracts.ts';
export {
  validateSceneEnvironment,
  validateSceneLight,
} from '../../sdk-core/src/scene/light/validate.ts';
