// Generated by scripts/generate-sdk-facade.ts.
export {
  assertCacheIdentity,
  assertCachePointer,
  assertCacheReady,
  assertCacheRoot,
  assertFormat,
  EngineError,
} from '../../sdk-core/src/contracts/cache.ts';
export type { PageSource } from '../../sdk-core/src/contracts/cache.ts';
export { assertManifestBinary, isBinaryManifest } from '../../sdk-core/src/manifest/binaryTypes.ts';
export type {
  ManifestBinaryDescriptor,
  SlimClusterManifest,
  SlimCulling,
  SlimPrimitive,
  SlimPrimitiveBinary,
  SlimStreams,
  SlimStructure,
} from '../../sdk-core/src/manifest/binaryTypes.ts';
export {
  blocksAcross,
  levelBlockBytes,
  PREVIEW_BASE,
  PREVIEW_MAX_LEVELS,
  previewBlockBytes,
  previewFirstLevel,
  previewIsWhole,
  previewLastLevel,
  previewLevelCount,
  previewLevelSize,
  previewPixelBytes,
} from '../../sdk-core/src/texture/previewLevels.ts';
export {
  clusterSphereValid,
  pageCarriesClusterError,
  primitiveIsDrawable,
  primitiveUsesClusterErrors,
  UNSPLIT_PASS,
} from '../../sdk-core/src/contracts/geometry.ts';
export type {
  ClusterGroup,
  ClusterManifest,
  ClusterStructure,
  CullingHierarchy,
  Page,
  Primitive,
  StreamBundle,
  StreamCatalogue,
} from '../../sdk-core/src/contracts/geometry.ts';
export { manifestBinaryRanges } from '../../sdk-core/src/manifest/binaryLayout.ts';
export type { Counts } from '../../sdk-core/src/manifest/binaryLayout.ts';
export {
  createPageIntegrationPlan,
  planPageIntegration,
  sortPages,
} from '../../sdk-core/src/page/integrationPlan.ts';
export type { PageIntegrationPlan } from '../../sdk-core/src/page/integrationPlan.ts';
export {
  decodeManifestBinary,
  decodeManifestPreviews,
} from '../../sdk-core/src/manifest/binaryDecode.ts';
export { encodeManifestBinary } from '../../sdk-core/src/manifest/binaryEncode.ts';
export {
  GEOMETRY_PAGE_CODEC,
  GEOMETRY_PAGE_FORMAT_VERSION,
  MANIFEST_BINARY_MAGIC,
  MANIFEST_BINARY_VERSION,
  COLUMN_KIND,
} from '../../sdk-core/src/manifest/binaryFormat.ts';
export type { ColumnKind } from '../../sdk-core/src/manifest/binaryFormat.ts';
export {
  PAGE_DECODE_FAILURES,
  PAGE_DECODE_PROTOCOL,
  pageDecodeFailureCode,
  pageDecodeWorkerCount,
} from '../../sdk-core/src/page/decodeContracts.ts';
export type {
  PageCutPage,
  PageCutPayload,
  PageDecodeAnswer,
  PageDecodeCancel,
  PageDecodeDone,
  PageDecodeFailed,
  PageDecodeFailureCode,
  PageDecodeGeometryPayload,
  PageDecodeOp,
  PageDecodeRequest,
  PageDecodeShare,
} from '../../sdk-core/src/page/decodeContracts.ts';
export {
  PAGE_INTEGRATION_FAILURES,
  PAGE_INTEGRATION_PROTOCOL,
  PAGE_SLICE_STRIDE,
  PAGE_SPEC_STRIDE,
  SLICE_OFFSET_WORDS,
  SLICE_PAGE_INDEX,
  SLICE_WORDS,
  SPEC_PAGE_INDEX,
  SPEC_STREAM_OFFSET,
  SPEC_TRIANGLES,
} from '../../sdk-core/src/page/integrationContracts.ts';
export type {
  PageIntegrationAnswer,
  PageIntegrationDone,
  PageIntegrationFailed,
  PageIntegrationFailureCode,
  PageIntegrationRequest,
} from '../../sdk-core/src/page/integrationContracts.ts';
export {
  PREVIEW_ATLAS_COLOR,
  PREVIEW_ATLAS_COVERAGE,
  PREVIEW_ATLAS_DATA,
  PREVIEW_ATLAS_NAMES,
  PREVIEW_BLOCK_BYTES,
  PREVIEW_BLOCK_FORMATS,
  PREVIEW_BLOCK_SIDE,
  PREVIEW_LAYOUT_NAMES,
  PREVIEW_LOSSLESS_FORMAT,
  TEXTURE_PREVIEW_VERSION,
} from '../../sdk-core/src/texture/previewFormat.ts';
export type {
  TextureBlockFormat,
  TextureLayout,
} from '../../sdk-core/src/texture/previewFormat.ts';
export { readPagedManifest } from '../../sdk-core/src/manifest/paged.ts';
export type {
  Texture,
  TextureColorSpace,
  TextureFilter,
  WrapMode,
} from '../../sdk-core/src/texture/contract.ts';
export type { TextureFrameMetrics } from '../../sdk-core/src/texture/metricsContracts.ts';
export { textureLevelFormat, textureLevelUrl } from '../../sdk-core/src/texture/levelUrl.ts';
export type { TextureLevelFormat } from '../../sdk-core/src/texture/levelUrl.ts';
export type { TexturePreview } from '../../sdk-core/src/texture/previewContracts.ts';
